apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-management-tool-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: project-management-tool
    spec:
      containers:
        - name: project-management-tool
          image: tchao98/project-management-tool
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      component: project-management-tool