apiVersion: v1
kind: Service
metadata:
  name: project-management-tool-load-balancer-service
spec:
  selector:
    component: project-management-tool
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer